#%RAML 1.0 Library

usage: Test

types:
    StringType:
        type: string
        minLength: 10
    EmptyObject:
    WithProperties:
        type: object
        properties:
            name?: string
            super:
                type: SuperType

    SuperType: object
    SubType:
        type: SuperType


    Enum:
        type: string
        enum:
        - v1
        - v2

