#%RAML 1.0 Library

usage: Defines locale related types.

types:
    LocalizedString:
        type: object
        properties:
            /^[a-z]{2}(-[A-Z]{2})?$/:
                type: string
        example:
          en: English
    CountryCode:
        type: string
        description: |
            A two-digit country code as per [ISO 3166-1 alpha-2](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2).
        pattern: ^[A-Z]{2}$

    CurrencyCode:
        type: string
        description: |
            The currency code compliant to [ISO 4217](https://en.wikipedia.org/wiki/ISO_4217).
        pattern: ^[A-Z]{3}$
