#%RAML 1.0 Library

usage: Defines the builtin RAML types.
        
annotationTypes:
    any:
        type: any
    time-only:
        type: time-only
    datetime:
        type: datetime
    datetime-only:
        type: datetime-only
    date-only:
        type: date-only
    number:
        type: number
    integer:
        type: integer
    boolean:
        type: boolean
    string:
        type: string
    nil:
        type: nil
    file:
        type: file
    array:
        type: array
    object:
        type: object
        
types:
    any:
        type: any
    time-only:
        type: time-only
    datetime:
        type: datetime
    datetime-only:
        type: datetime-only
    date-only:
        type: date-only
    number:
        type: number
    integer:
        type: integer
    boolean:
        type: boolean
    string:
        type: string
    nil:
        type: nil
    file:
        type: file
    array:
        type: array
    object:
        type: object

securitySchemes:
    # the null security scheme
    null:
