#%RAML 1.0 Library

usage: Type with an annotation
(PackageName): package

annotationTypes:
    PackageName:
        type: string
    TypeMapping:
        properties:
          package:
            type: string
          typeName:
            type: string


types:
    AnnotatedType:
        (PackageName): package
        (TypeMapping):
          package: java.lang
          typeName: String
        type: object
        properties:
            default:
                type: string
