#%RAML 1.0 Library

usage: Type with an annotation
(PackageName): package

annotationTypes:
    PackageName:
        type: string

types:
    AnnotatedType:
        (PackageName): package
        type: object

