#%RAML 1.0 Overlay
usage: An example extension
extends: api.raml


/{project}:
  post:
    displayName: overlay update project
    body:
      application/json:
        displayName: overlay body update


