on:
  - push

name: CI

jobs:
  ci:
    name: Build and test

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'

      - name: Build and Test
        run: ./gradlew --build-cache clean check
