on:
  - workflow_dispatch

name: Release to Maven Central

permissions:
  contents: write
  actions: write

jobs:
  release:
    name: Build and release

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: "11"
          distribution: 'temurin'

      - run: scripts/setup-signing-key.sh
        env:
          DECRYPTER: ${{ secrets.DECRYPTER }}
          SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
          PASSPHRASE: ${{ secrets.PASSPHRASE }}

      - name: Build and Release
        run: export VERSION="0.2.0-`date '+%Y%m%d%H%M%S'`"; ./gradlew -Pversion=$VERSION clean check publishMavenPublicationToSonatype closeAndReleaseSonatypeStagingRepository writeVersionToReadme
        env:
          CTP_OSS_USER: ${{ secrets.OSS_USER }}
          CTP_OSS_SECRET: ${{ secrets.OSS_SECRET }}


      - uses: stefanzweifel/git-auto-commit-action@v4.6.0
        with:
          file_pattern: "README.md"
          commit_message: "TASK: Updating version in README"
          commit_user_name: Auto Mation
          commit_user_email: automation@commercetools.com
          commit_author: Auto Mation <automation@commercetools.com>
